name: velhealthaiwork
description: "HealthLink is a comprehensive healthcare data platform designed to bridge the gap between patients and their medical records across multiple healthcare providers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  intl: ^0.19.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
